---
- name: Create interface files
  ansible.builtin.template:
    src: interface.conf.j2
    dest: "/etc/network/interfaces.d/{{ item.key }}.conf"
    mode: "644"
  with_items:
    - "{{ interfaces | dict2items }}"
  notify:
    - Restart networking
