---
- name: Create /etc/udev/rules.d
  ansible.builtin.file:
    name: /etc/udev/rules.d
    state: directory
    mode: "755"

- name: Template out to udev.d
  ansible.builtin.template:
    src: udev.rules.j2
    dest: "/etc/udev/rules.d/{{ item.key }}.rules"
    mode: "644"
  with_items:
    - "{{ udev_rules | dict2items }}"
  notify:
    - Update initramfs
    - Trigger udev add
